<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Get Eligibility</name>
  <uuid>046de1c3-914b-466d-a34a-3b6acba8234d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the main service eligibility computed from
		professional being professional , 
		sharePercentage being sharePercentage , 
		years being 'Number of Years' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
