<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Years is more than one</name>
  <uuid>992e5cf6-e950-48f8-b36b-916dc9375677</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Number of Years' is more than 1
    and the amount of decision is more than -1
then
	set decision to a new Decision_result where
		the amount is 0 , 
		the msg is "عدد السنوات يجب ان يساوي ١ سنة" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
