<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Validate Number of Years</name>
  <uuid>543cf643-c02e-4b27-918c-ccd86bd87fb1</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Number of Years' ≠ 3
then
	set decision to a new Amount_VAT where
		the VAT is 0 , 
		the amount_VAT is 0 , 
		the msg is "عدد سنوات التجديد يجب ان تساوي ٣ سنوات" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
