<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Get Company Entrepreneur</name>
  <uuid>b68ad604-abbe-46fe-af67-f0aa8eca075b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	entrepreneur
then
	set decision to a new Decision_result where
		the amount is 2000 , 
		the msg is "تكلفة ترخيص الاستثمار لرائد الأعمال المتعاقد مع جامعة أو حاضنة أعمال " ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
