<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Get Eligibility</name>
  <uuid>6256439d-5be9-4997-a096-7503554cb093</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the main service eligibility computed from
		professional being professional , 
		sharePercentage being sharePercentage , 
		years being Years ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
