<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Get_CompanyHQ_Renewal_Cost</name>
  <uuid>9420480c-591c-4678-a626-de777c45f02b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	classification is "Silver"
	and 'Has HQ in KSA' 
	and renewal_Year is more than 1
    and entrepreneur is false 
    and the amount of decision > -1 
then
	set decision to a new Decision_result where
		the amount is 2000 , 
		the msg is "تكلفة تجديد ترخيص الاستثمار المنشأة تعمل بصفتها مقراً إقليمياً في المملكة ومصنفة فضية " ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
