<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Main Service Eligibility</name>
  <uuid>64fa442b-878a-4940-b891-29c8b3e06b4c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the main service eligibility computed from
		professional being professional , 
		sharePercentage being sharePercentage , 
		years being renewal_Year ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
