<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Renewal Year is more than 1</name>
  <uuid>3af0e863-32f6-46e9-b9d4-d78544517be8</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	renewal_Year is 1
then
	set decision to a new Decision_result where
		the amount is 0 , 
		the msg is "عدد سنوات التجديد يجب ان تكون اكبر من ١" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
