<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>a61822da-9876-4494-8505-1160b864c1bd</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[
	set decision to a new ML_Custom_Output where 
		the prediction is the prediction of 'ML model invocation' ,
		 the probabilities are the probabilities of 'ML model invocation';]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
